module.exports = {
	parserOptions: {
		ecmaVersion: 2019,
	},
	rules: {
		'for-direction': 'off',
		'getter-return': 'off',
		'no-await-in-loop': 'off',
		'no-compare-neg-zero': 'error',
		'no-cond-assign': 'warn',
		'no-console': 'off',
		'no-control-regex': 'off',
		'no-debugger': 'error',
		'no-dupe-args': 'error',
		'no-dupe-keys': 'error',
		'no-duplicate-case': 'error',
		'no-empty': 'off',
		'no-empty-character-class': 'error',
		'no-ex-assign': 'off',
		'no-extra-boolean-cast': 'off',
		'no-extra-parens': 'off',
		'no-extra-semi': 'error',
		'no-func-assign': 'off',
		'no-inner-declarations': 'off',
		'no-invalid-regexp': 'warn',
		'no-irregular-whitespace': ['error', { skipStrings: true, skipComments: true, skipRegExps: true, skipTemplates: true }],
		'no-obj-calls': 'warn',
		'no-prototype-builtins': 'off',
		'no-regex-spaces': 'warn',
		'no-sparse-arrays': 'warn',
		'no-template-curly-in-string': 'off',
		'no-unexpected-multiline': 'error',
		'no-unreachable': 'warn',
		'no-unsafe-finally': 'warn',
		'no-unsafe-negation': 'error',
		'use-isnan': 'error',
		'valid-jsdoc': 'off',
		'valid-typeof': 'error',
		'accessor-pairs': 'off',
		'array-callback-return': 'off',
		'block-scoped-var': 'error',
		'class-methods-use-this': 'off',
		'complexity': 'off',
		'consistent-return': 'off',
		'curly': ['error', 'multi-line', 'consistent'],
		'default-case': 'off',
		'dot-location': ['error', 'property'],
		'dot-notation': ['error', { allowKeywords: true, allowPattern: '(^[A-Z])|(^[a-z]+(_[a-z]+)+$)' }],
		'eqeqeq': ['error', 'smart'],
		'guard-for-in': 'warn',
		'no-alert': 'error',
		'no-caller': 'error',
		'no-case-declarations': 'error',
		'no-div-regex': 'off',
		'no-else-return': 'warn',
		'no-empty-function': 'off',
		'no-empty-pattern': 'off',
		'no-eq-null': 'warn',
		'no-eval': 'warn',
		'no-extend-native': 'warn',
		'no-extra-bind': 'off',
		'no-extra-label': 'warn',
		'no-fallthrough': 'off',
		'no-floating-decimal': 'error',
		'no-global-assign': 'off',
		'no-implicit-coercion': 'error',
		'no-implicit-globals': 'off',
		'no-implied-eval': 'error',
		'no-invalid-this': 'off',
		'no-iterator': 'off',
		'no-labels': 'off',
		'no-lone-blocks': 'off',
		'no-loop-func': 'off',
		'no-magic-numbers': 'off',
		'no-multi-spaces': ['error', { ignoreEOLComments: true }],
		'no-multi-str': 'error',
		'no-new': 'off',
		'no-new-func': 'warn',
		'no-new-wrappers': 'warn',
		'no-octal': 'error',
		'no-octal-escape': 'error',
		'no-param-reassign': 'off',
		'no-proto': 'off',
		'no-redeclare': 'error',
		'no-restricted-properties': 'off',
		'no-return-assign': 'off',
		'no-return-await': 'warn',
		'no-script-url': 'off',
		'no-self-assign': 'error',
		'no-self-compare': 'warn',
		'no-sequences': 'error',
		'no-throw-literal': 'error',
		'no-unused-expressions': 'off',
		'no-unused-labels': 'error',
		'no-useless-call': 'off',
		'no-useless-concat': 'warn',
		'no-useless-escape': 'off',
		'no-useless-return': 'warn',
		'no-void': 'off',
		'no-warning-comments': 'off',
		'no-with': 'error',
		'prefer-promise-reject-errors': 'off',
		'radix': ['error', 'as-needed'],
		'require-await': 'off',
		'vars-on-top': 'off',
		'wrap-iife': ['error', 'inside'],
		'yoda': 'error',
		'strict': ['error', 'never'],
		'init-declarations': 'off',
		'no-catch-shadow': 'error',
		'no-delete-var': 'error',
		'no-label-var': 'error',
		'no-restricted-globals': 'off',
		'no-shadow': 'warn',
		'no-shadow-restricted-names': 'error',
		'no-undef': 'error',
		'no-undef-init': 'off',
		'no-undefined': 'off',
		'no-unused-vars': 'warn',
		'no-use-before-define': 'error',
		'callback-return': 'off',
		'global-require': 'off',
		'handle-callback-err': 'off',
		'no-buffer-constructor': 'error',
		'no-mixed-requires': 'error',
		'no-new-require': 'error',
		'no-path-concat': 'warn',
		'no-process-env': 'off',
		'no-process-exit': 'off',
		'no-restricted-modules': 'off',
		'no-sync': 'off',
		'array-bracket-newline': ['error', 'consistent'],
		'array-bracket-spacing': ['error', 'never', { singleValue: false, objectsInArrays: false, arraysInArrays: false }],
		'array-element-newline': 'off',
		'block-spacing': ['error', 'always'],
		'brace-style': ['error', '1tbs', { allowSingleLine: true }],
		'camelcase': 'off',
		'capitalized-comments': 'off',
		'comma-dangle': ['error', 'always-multiline'],
		'comma-spacing': ['error', { before: false, after: true }],
		'comma-style': ['error', 'last'],
		'computed-property-spacing': ['error', 'never'],
		'consistent-this': ['error', 'self'],
		'eol-last': ['error', 'always'],
		'func-call-spacing': ['error', 'never'],
		'func-name-matching': ['warn', 'always'],
		'func-names': ['warn', 'as-needed'],
		'func-style': 'off',
		'function-paren-newline': ['error', 'consistent'],
		'id-blacklist': 'off',
		'id-length': 'off',
		'id-match': 'off',
		'indent': ['error', 'tab', { SwitchCase: 1 }],
		'jsx-quotes': ['error', 'prefer-double'],
		'key-spacing': ['error', { beforeColon: false, afterColon: true, mode: 'strict' }],
		'keyword-spacing': ['error', { before: true, after: true }],
		'line-comment-position': 'off',
		'linebreak-style': ['error', 'unix'],
		'lines-around-comment': 'off',
		'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
		'max-depth': 'off',
		'max-len': 'off',
		'max-lines': 'off',
		'max-nested-callbacks': 'off',
		'max-params': 'off',
		'max-statements': 'off',
		'max-statements-per-line': ['error', { max: 1 }],
		'multiline-comment-style': 'off',
		'multiline-ternary': ['error', 'always-multiline'],
		'new-cap': 'off',
		'new-parens': 'error',
		'newline-per-chained-call': ['error', { ignoreChainWithDepth: 3 }],
		'no-array-constructor': 'off',
		'no-bitwise': 'off',
		'no-inline-comments': 'off',
		'no-lonely-if': 'error',
		'no-mixed-operators': 'error',
		'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
		'no-multi-assign': 'warn',
		'no-multiple-empty-lines': 'error',
		'no-nested-ternary': 'off',
		'no-new-object': 'error',
		'no-plusplus': 'off',
		'no-restricted-syntax': 'off',
		'no-tabs': 'off',
		'no-ternary': 'off',
		'no-trailing-spaces': 'error',
		'no-underscore-dangle': 'off',
		'no-unneeded-ternary': 'off',
		'no-whitespace-before-property': 'error',
		'nonblock-statement-body-position': 'off',
		'object-curly-newline': ['error', { multiline: true, consistent: true }],
		'object-curly-spacing': ['error', 'always'],
		'object-property-newline': 'off',
		'one-var': ['error', 'never'],
		'one-var-declaration-per-line': 'off',
		'operator-assignment': ['error', 'always'],
		'operator-linebreak': ['error', 'before'],
		'padded-blocks': ['error', 'never'],
		'padding-line-between-statements': 'off',
		'quote-props': ['error', 'as-needed', { keywords: true, numbers: false }],
		'quotes': ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
		'require-jsdoc': 'off',
		'semi': ['error', 'always', { omitLastInOneLineBlock: false }],
		'semi-spacing': ['error', { before: false, after: true }],
		'semi-style': ['error', 'last'],
		'sort-keys': 'off',
		'sort-vars': 'off',
		'space-before-blocks': ['error', 'always'],
		'space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
		'space-in-parens': ['error', 'never'],
		'space-infix-ops': ['error', { int32Hint: true }],
		'space-unary-ops': ['error', { words: true, nonwords: false }],
		'spaced-comment': ['error', 'always'],
		'switch-colon-spacing': ['error', { after: true, before: false }],
		'template-tag-spacing': ['error', 'never'],
		'unicode-bom': ['error', 'never'],
		'wrap-regex': 'off',
		'arrow-body-style': 'off',
		'arrow-parens': ['error', 'as-needed', { requireForBlockBody: false }],
		'arrow-spacing': ['error', { before: true, after: true }],
		'constructor-super': 'error',
		'generator-star-spacing': ['error', 'before'],
		'no-class-assign': 'warn',
		'no-confusing-arrow': 'off',
		'no-const-assign': 'error',
		'no-dupe-class-members': 'error',
		'no-duplicate-imports': ['error', { includeExports: false }],
		'no-new-symbol': 'warn',
		'no-restricted-imports': 'off',
		'no-this-before-super': 'error',
		'no-useless-computed-key': 'error',
		'no-useless-constructor': 'error',
		'no-useless-rename': 'error',
		'no-var': 'error',
		'object-shorthand': 'off',
		'prefer-arrow-callback': 'error',
		'prefer-const': ['error', { destructuring: 'all' }],
		'prefer-destructuring': 'off',
		'prefer-numeric-literals': 'off',
		'prefer-rest-params': 'warn',
		'prefer-spread': 'error',
		'prefer-template': 'warn',
		'require-yield': 'warn',
		'rest-spread-spacing': ['error', 'never'],
		'sort-imports': 'off',
		'symbol-description': 'warn',
		'template-curly-spacing': ['error', 'never'],
		'yield-star-spacing': ['error', 'before'],
	},
};
